# Generated by Django 3.1.3 on 2020-12-02 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cif', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('postal_code', models.IntegerField(max_length=6)),
                ('country', models.CharField(max_length=20)),
                ('creditcard_number', models.IntegerField(max_length=10)),
            ],
            options={
                'db_table': 'billinginfo',
                'ordering': ['cif'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('billinginfo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.billinginfo')),
            ],
            options={
                'db_table': 'company',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'project',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tag',
                'ordering': ['estado'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.company')),
                ('projects', models.ManyToManyField(to='api.Project')),
            ],
            options={
                'db_table': 'user',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.project'),
        ),
        migrations.AddField(
            model_name='task',
            name='tag',
            field=models.ManyToManyField(to='api.Tag'),
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user'),
        ),
    ]
