# Generated by Django 3.1.3 on 2020-12-02 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201202_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='nombre',
            field=models.CharField(max_length=60),
        ),
    ]
