# Generated by Django 3.1.3 on 2020-12-03 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201203_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='billinginfo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.billinginfo'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.project'),
        ),
    ]
