# Generated by Django 3.1.3 on 2020-12-15 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201204_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='tag',
            new_name='tags',
        ),
        migrations.AlterField(
            model_name='company',
            name='billinginfo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.billinginfo'),
        ),
    ]
